// Package audit implements the L7 System Audit boundary.
// It performs panoptic, bi-directional verification across L2 (Registry),
// L3 (Normative Intent), L4 (Verification), and L5 (Physical Disk) to mathematically
// prove system closure and detect structural drift.
//
// Authority Class: 2 (Logic / Orchestration Boundary)
package audit

import (
	"context"
	"errors"
	"fmt"
	"reflect"

	"github.com/sfeeser/genesis/internal/identity"
	"github.com/sfeeser/genesis/internal/registry"
	"github.com/sfeeser/genesis/internal/scanner"
	"github.com/sfeeser/genesis/internal/spec"
)

// Sentinel boundary errors for the Audit layer.
var (
	ErrAuditFailed   = errors.New("system audit failed to execute to completion")
	ErrDriftDetected = errors.New("architectural or physical drift detected")
	ErrOrphanNode    = errors.New("node exists in L3 normative intent but is missing from L2 registry")
	ErrGhostNode     = errors.New("node exists in L2 registry but is missing from L3 intent")
	ErrSourceMissing = errors.New("physical source file is missing or unparseable")
	ErrLogicMismatch = errors.New("physical AST logic, contract, or dependency hash diverges from registry metadata")
)

// DriftViolation represents a mathematically proven divergence between engine layers.
type DriftViolation struct {
	NodeID      string // Canonical string representation or System Component
	Description string
	Severity    string // "FATAL" or "WARN"
}

// Report represents the deterministic evidence generated by an L7 audit.
type Report struct {
	Environment registry.EnvironmentSentinel
	NodesPassed int
	NodesFailed int
	Violations  []DriftViolation
}

// IsClean proves mathematically that the system exhibits zero structural drift.
func (r Report) IsClean() bool {
	return r.NodesFailed == 0 && len(r.Violations) == 0
}

// Registry mandates the L2 contract required for full bi-directional auditing.
type Registry interface {
	GetNode(ctx context.Context, id identity.NodeID) (registry.NodeDetail, error)
	ListNodes(ctx context.Context) ([]registry.NodeDetail, error)
	GetEnvironment(ctx context.Context) (registry.EnvironmentSentinel, error)
}

// Workspace mandates the L5 contract required to prevent path logic leaks.
type Workspace interface {
	LoadNormativeIntent(ctx context.Context) (spec.Book, error)
	ReadWorkspaceFile(ctx context.Context, relativePath string) ([]byte, error)
	CaptureEnvironment(ctx context.Context, buildTags, buildFlags []string) (registry.EnvironmentSentinel, error)
	ResolveSourceFile(id identity.NodeID) (string, error)
}

// Scanner defines the verification boundaries required from L4.
// It is escalated to demand cryptographic D-ID proofs for panoptic closure.
type Scanner interface {
	Scan(ctx context.Context, source []byte, id identity.NodeID) (scanner.ParsedSymbol, error)
	// ComputeDependencyHash guarantees L4 can mathematically prove the dependency subgraph (D-ID).
	ComputeDependencyHash(ctx context.Context, source []byte, id identity.NodeID) (string, error)
}

// Auditor defines the L7 contract for verifying cross-boundary structural integrity.
type Auditor interface {
	ExecuteFullSweep(ctx context.Context) (Report, error)
	VerifyNode(ctx context.Context, id identity.NodeID) error
}

// systemAuditor is the concrete implementation of the panoptic audit boundary.
type systemAuditor struct {
	store     Registry
	workspace Workspace
	scanner   Scanner
}

// NewAuditor initializes the L7 panoptic verifier with strictly governed interface access.
func NewAuditor(store Registry, ws Workspace, sc Scanner) Auditor {
	return &systemAuditor{
		store:     store,
		workspace: ws,
		scanner:   sc,
	}
}

// ExecuteFullSweep performs a comprehensive, bi-directional cross-layer audit.
func (a *systemAuditor) ExecuteFullSweep(ctx context.Context) (Report, error) {
	if err := ctx.Err(); err != nil {
		return Report{}, fmt.Errorf("%w: %v", ErrAuditFailed, err)
	}

	report := Report{
		Violations: make([]DriftViolation, 0),
	}

	// 1. Audit the Physical Environment Baseline
	expectedEnv, err := a.store.GetEnvironment(ctx)
	if err != nil {
		return report, fmt.Errorf("%w: failed to read baseline environment from L2: %v", ErrAuditFailed, err)
	}
	
	env, err := a.workspace.CaptureEnvironment(ctx, expectedEnv.BuildTags, expectedEnv.BuildFlags)
	if err != nil {
		return report, fmt.Errorf("%w: failed to capture physical L5 environment: %v", ErrAuditFailed, err)
	}
	report.Environment = env

	// Mathematical Environment Drift Check
	if !reflect.DeepEqual(expectedEnv, env) {
		a.addViolation(&report, "ENVIRONMENT", fmt.Sprintf("%v: current physical toolchain/graph does not match registry baseline", ErrDriftDetected), "FATAL")
	}

	// 2. Load and Validate Normative Intent (L3)
	book, err := a.workspace.LoadNormativeIntent(ctx)
	if err != nil {
		return report, fmt.Errorf("%w: normative intent corrupted: %v", ErrAuditFailed, err)
	}

	// 3. Sweep Direction A: L3 (Intent) -> L2 (Registry)
	intentMap := make(map[string]struct{})
	for _, pkg := range book.Packages {
		for _, n := range pkg.Nodes {
			id, err := identity.NewNodeID(n.Kind, n.Visibility, book.Module, pkg.Path, n.ReceiverShape, n.Symbol, n.Arity)
			if err != nil {
				a.addViolation(&report, "<invalid>", fmt.Sprintf("L3 Intent violates L1 physical grammar: %v", err), "FATAL")
				continue
			}
			
			canon, err := id.Canonical()
			if err != nil {
				a.addViolation(&report, "<unprovable>", fmt.Sprintf("failed to canonicalize L1 physical identity: %v", err), "FATAL")
				continue
			}
			
			intentMap[canon] = struct{}{}

			if err := a.VerifyNode(ctx, id); err != nil {
				a.addViolation(&report, canon, err.Error(), "FATAL")
			} else {
				report.NodesPassed++
			}
		}
	}

	// 4. Sweep Direction B: L2 (Registry) -> L3 (Intent)
	l2Nodes, err := a.store.ListNodes(ctx)
	if err != nil {
		return report, fmt.Errorf("%w: failed to list L2 registry nodes: %v", ErrAuditFailed, err)
	}

	for _, node := range l2Nodes {
		canon, err := node.NodeID.Canonical()
		if err != nil {
			a.addViolation(&report, "<unprovable>", fmt.Sprintf("registry node has invalid physical identity: %v", err), "FATAL")
			continue
		}
		if _, exists := intentMap[canon]; !exists {
			a.addViolation(&report, canon, ErrGhostNode.Error(), "FATAL")
		}
	}

	return report, nil
}

// VerifyNode performs a targeted, synchronous audit of a single physical node,
// rigorously proving its alignment across structural domains and all maturity obligations.
func (a *systemAuditor) VerifyNode(ctx context.Context, id identity.NodeID) error {
	canon, err := id.Canonical()
	if err != nil {
		return fmt.Errorf("invalid physical identity: %w", err)
	}

	// 1. Verify L2 Registry Presence
	nodeDetail, err := a.store.GetNode(ctx, id)
	if err != nil {
		if errors.Is(err, registry.ErrNodeNotFound) {
			return fmt.Errorf("%w: %s", ErrOrphanNode, canon)
		}
		return fmt.Errorf("registry read failure: %w", err)
	}

	if nodeDetail.Maturity == registry.MaturityDraft {
		return nil
	}

	// 2. Resolve Exact Physical Target Path via L5 Authority
	targetPath, err := a.workspace.ResolveSourceFile(id)
	if err != nil {
		return fmt.Errorf("failed to map target source file: %w", err)
	}

	// 3. Retrieve Physical Source
	sourceBytes, err := a.workspace.ReadWorkspaceFile(ctx, targetPath)
	if err != nil {
		return fmt.Errorf("%w: file missing at %s", ErrSourceMissing, targetPath)
	}

	// 4. Scan and Parse AST via L4
	parsedSymbol, err := a.scanner.Scan(ctx, sourceBytes, id)
	if err != nil {
		return fmt.Errorf("%w: L4 scanner rejected physical source: %v", ErrSourceMissing, err)
	}

	// 5. Enforce Maturity-Bound Cryptographic Obligations
	
	if requiresContract(nodeDetail.Maturity) {
		actualCID := identity.ComputeContractID(parsedSymbol.Signature)
		if actualCID != nodeDetail.ContractID {
			return fmt.Errorf("%w: ContractID drift. Expected %s, got %s", ErrLogicMismatch, nodeDetail.ContractID, actualCID)
		}
	}

	if requiresLogic(nodeDetail.Maturity) {
		actualLID := identity.ComputeLogicHash(parsedSymbol.NormalizedAST)
		if actualLID != nodeDetail.LogicHash {
			return fmt.Errorf("%w: LogicHash drift. Expected %s, got %s", ErrLogicMismatch, nodeDetail.LogicHash, actualLID)
		}
	}

	if requiresDependency(nodeDetail.Maturity) {
		if nodeDetail.DependencyHash == "" {
			return fmt.Errorf("%w: missing DependencyHash for maturity %s", ErrLogicMismatch, nodeDetail.Maturity)
		}
		// Complete Panoptic Proof: L4 must now mathematically prove the D-ID.
		actualDID, err := a.scanner.ComputeDependencyHash(ctx, sourceBytes, id)
		if err != nil {
			return fmt.Errorf("failed to compute physical dependency hash: %w", err)
		}
		if actualDID != nodeDetail.DependencyHash {
			return fmt.Errorf("%w: DependencyHash drift. Expected %s, got %s", ErrLogicMismatch, nodeDetail.DependencyHash, actualDID)
		}
	}

	return nil
}

// --- Internal Audit Utilities ---

func requiresContract(m registry.Maturity) bool {
	return m == registry.MaturityAnchored || m == registry.MaturityHydrated || m == registry.MaturitySequenced || m == registry.MaturityImplemented
}

func requiresLogic(m registry.Maturity) bool {
	return m == registry.MaturityHydrated || m == registry.MaturitySequenced || m == registry.MaturityImplemented
}

func requiresDependency(m registry.Maturity) bool {
	return m == registry.MaturitySequenced || m == registry.MaturityImplemented
}

func (a *systemAuditor) addViolation(r *Report, idStr string, desc string, severity string) {
	r.Violations = append(r.Violations, DriftViolation{
		NodeID:      idStr,
		Description: desc,
		Severity:    severity,
	})
	r.NodesFailed++
}
